### ISSUE TITLE
Allow the administrator to define known outputs and ignore the output of specific packages or hooks

### ISSUE THREAD

**Issue by Trumeet** [isjerryxiao/pacroller#4]
Could you add the feature that allows the administrator to specific custom known outputs in the `config.json`? This is necessary for environments that involve custom or private packages or hooks that would be not appropriate to add to the source. Also, it would be awesome to allow the administrator to ignore the output of specific packages or hooks according to the needs of local environment. Thanks.

**Comment by isjerryxiao** [comment]
implemented
