### ISSUE TITLE
Can not continue error.

### ISSUE THREAD

**Issue by vvlaw** [isjerryxiao/pacroller#8]
ERROR - Cannot continue, a previous error PackageHold(['hold package linux is going to be upgraded from 6.0.8.arch1-1 to 6.0.9.arch1-1']) is still present. Please resolve this issue and run reset.

**Comment by isjerryxiao** [comment]
This tool is mainly designed for server applications, so it blocks update on error by default. If you use that in a desktop environment, you may remove linux from "hold" list in /etc/pacroller/config.json.  
Also Please READ THE TEXT ABOVE, `Please resolve this issue and run reset.`  
Which tells you to resolve this issue, in this case nothing, and then run `pacroller reset`

**Comment by vvlaw** [comment]
thanks. it works.
